name: currency_converter
description: A new Flutter project.
version: 1.1.0+8
# x.y.z+n
# x.y.z = version number(Flutter) = build-name(Flutter) = versionName(Android)
# n = build-number (Flutter) = versionCode (Android)

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/euro.png" 
#Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">
#Pixel perfect</a> 
#from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true